#!/bin/sh

fuzzy_preview() {
  fzf -e \
    --preview "bat --color=always {}" \
    --preview-window right,70% \
    --bind up:preview-page-up,down:preview-page-down \
    --header "Open File" \
    --header-first \
    --preview-label "File Preview" \
    --padding 1
}

if [[ -d .git ]]; then
  selected=$(git ls-files | fuzzy_preview)
  [[ -z $selected ]] && exit 0 || nvim $selected
else
  selected=$(find . -not -type d | fuzzy_preview)
  [[ -z $selected ]] && exit 0 || nvim $selected
fi
