#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # FUZZY FIND DIRECTORIES
    selected=$(find ~/* -type d | fzf)
fi

# EXITS IF NO SELECTED
if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# CREATE NEW TMUX SESSION IF TMUX SERVER IS NOT RUNNING
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

# CREATE NEW TMUX SESSION IF THE SELECTED BASENAME IS NOT A SESSION
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

# ATTACH TO TMUX SESSION IF TMUX HAS A SESSION SIMILAR TO SELECTED BASENAME AND IF HAS NO RUNNING TMUX SESSION (OR CURRENTLY DEATTACHED)
if tmux has-session -t $selected_name && [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
else
    # SWITCH TO SELECTED CLIENT IF TMUX SERVER IS RUNNING
    tmux switch-client -t $selected_name
fi

