vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
require 'config.lazy'
require 'config.autocmds'
require 'config.options'
require 'config.keymaps'
require 'config.highlights'
require 'config.neovide'
