#!/bin/sh

workspace="$(git rev-parse --show-toplevel 2> /dev/null)"
[ -z "$workspace" ] && exit 0

ORANGE='\033[0;33m'
RED='\033[0;91m'
CYAN='\033[0;36m'

dirty_preview() {
  fzf -e \
    --preview "bat --style=changes,header,grid --theme=1337 --color=always {}" \
    --preview-window right,60% \
    --bind up:preview-page-up,down:preview-page-down \
    --header "$(printf " ${ORANGE}Open File ")" \
    --header-first \
    --preview-label "$(printf " ${ORANGE}File Preview ")" \
    --border-label "$(printf "${RED} Dirty Files ")" \
    --padding 1 \
    --prompt " " \
    --pointer ""
}

dirty_files=$(git diff --name-only --diff-filter=M "$workspace" 2> /dev/null | xargs -I {} printf "${RED}${workspace}/{}\n")

untracked_files=$(git ls-files "$workspace" --full-name --exclude-standard --others 2> /dev/null | xargs -I {} printf "${CYAN}${workspace}/{}\n")

[  -z "$dirty_files" ] && [ -z "$untracked_files" ] && echo "no dirty files, working tree clean" && exit 0

[ -z "$dirty_files" ] && selected=$(echo "$untracked_files" | tr ' ' '\n' | dirty_preview)
[ -z "$untracked_files" ] && selected=$(echo "$dirty_files" | tr ' ' '\n' | dirty_preview)

[ -n "$dirty_files" ] && [ -n "$untracked_files" ] && selected=$(echo "$dirty_files" "$untracked_files" | tr ' ' '\n' | dirty_preview)

[ -z "$selected" ] || nvim "$selected"
