#!/bin/sh

ORANGE='\033[0;33m'

fuzzy_preview() {
  fzf -e \
    --preview "bat --theme=1337 --color=always {}" \
    --preview-window right,70% \
    --bind up:preview-page-up,down:preview-page-down \
    --header "$(printf "${ORANGE}Select File")" \
    --border-label "$(printf " ${ORANGE}Open File ")" \
    --header-first \
    --preview-label "$(printf " ${ORANGE}File Preview ")" \
    --padding 1 \
    --prompt " " \
    --pointer ""
}

selected=$(rg --files --sort-files --hidden --glob="!{**.git/*,**/node_modules/*,.cache,**.jpg,**.png,**.mp3,**.mp4,**.rpm}" | fuzzy_preview)
[ -z "$selected" ] || nvim "$selected"
