#!/bin/sh

CYAN='\033[0;36m'
NC='\033[0m'
ORANGE='\033[0;33m'
RED='\033[0;91m'

[[ -z $1 ]] || git checkout $1
[[ -z $1 ]] || exit 0

checkout_branch() {
  local selected=$(git branch 2> /dev/null |fzf --border=rounded --border-label "$(printf " ${ORANGE}Checkout Branch ")" --header-first --header "$(printf " ${ORANGE}Checkout Branch ")" --margin=25%)
  [[ -z $selected ]] && exit 0
  git checkout $selected 2> /dev/null
}

checkout_commit() {
  local selected=$(git log --oneline --color=always 2> /dev/null | fzf --ansi --border=sharp --header-first --header "Checkout Commit" --margin=5%)
  [[ -z $selected ]] && exit 0
  commit_id=$(echo $selected | awk '{print $1}')
  git checkout $commit_id 2> /dev/null
}

checkout_what() {
  local selected=$(echo "branch commit" | tr ' ' '\n' | fzf --ansi --border=rounded --border-label "$(printf " ${ORANGE}Checkout What? ")" --header-first --header "$(printf " ${ORANGE}Checkout What? ")" --margin=25%)
  [[ -z $selected ]] && exit 0
  [[ "$selected" = "branch" ]] && checkout_branch
  [[ "$selected" = "commit" ]] && checkout_commit
}

checkout_what
