#!/bin/sh

ORANGE='\033[0;33m'
fuzzy_preview() {
  fzf -e \
    --header "$(printf "${ORANGE}Select File")" \
    --header-first \
    --border=rounded \
    --border-label " Unstage File " \
    --margin 15%,15%
}

[[ -z $1 ]] || git restore --stage $1
[[ -z $1 ]] || exit 0

staged_files=$(git diff --name-only --cached)
[[ -z $staged_files ]] && echo "No staged files, nothing to unstage" && exit 0
workspace=$(git rev-parse --show-toplevel)
selected=$(echo $staged_files | tr ' ' '\n' | fuzzy_preview)
[[ -z $selected ]] || git restore --stage $workspace/$selected
