#!/bin/sh

[ -z "$(git rev-parse --show-toplevel 2> /dev/null)" ] && exit 0

CYAN='\033[0;36m'
GREEN='\033[1;32m'
RED='\033[0;91m'
fuzzy_preview() {
  fzf -e \
    --header "$(printf "${CYAN}Select File")" \
    --header-first \
    --border=rounded \
    --border-label "$(printf " ${RED}Unstage File ")" \
    --margin 15%,15% \
    --pointer "" \
    --prompt "  "
}

[ -z "$1" ] || git restore --stage "$1"
[ -z "$1" ] || exit 0

staged_files=$(git diff --name-only --cached)
[ -z "$staged_files" ] && echo "No staged files, nothing to unstage" && exit 0
workspace=$(git rev-parse --show-toplevel)
selected=$(printf "${GREEN}${staged_files}" | tr ' ' '\n' | fuzzy_preview)
[ -z "$selected" ] || git restore --stage "$workspace"/"$selected"
