#!/bin/sh

workspace=$(git rev-parse --show-toplevel 2> /dev/null)
[ -z "$workspace" ] && exit 0

RED='\033[0;91m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'

dirty_preview() {
  fzf -e \
    --header "$(printf " ${CYAN}Git Restore ") " \
    --header-first \
    --border=rounded \
    --border-label "$(printf " ${CYAN}Restore ${RED}Deleted ${WHITE}File ")" \
    --margin 15%,15% \
    --prompt " " \
    --pointer ""
}

dirty_files=$(git diff --name-only --diff-filter=D "$workspace" 2> /dev/null | xargs -I {} printf "${RED}{}\n")
[ -z "$dirty_files" ] || selected=$(echo "$dirty_files" | tr ' ' '\n' | dirty_preview); [ -z "$selected" ] || git restore "$workspace/$selected"
