#!/bin/sh

[ -z "$(git rev-parse --show-toplevel 2> /dev/null)" ] && exit 0

RED='\033[0;91m'
CYAN='\033[0;36m'

dirty_preview() {
  fzf -e \
    --header "$(printf " ${CYAN}Restore File") " \
    --header-first \
    --border=rounded \
    --border-label "$(printf " ${CYAN}Git Restore ")" \
    --margin 15%,15% \
    --prompt " " \
    --pointer ""
}

dirty_files=$(git ls-files "$(git rev-parse --show-toplevel 2> /dev/null)" -m 2> /dev/null | xargs -I {} printf "${RED}{}\n")
[ -z "$dirty_files" ] || selected=$(echo "$dirty_files" | tr ' ' '\n' | dirty_preview); [ -z "$selected" ] || git restore "$selected"
