#!/bin/sh

[[ -z $1 ]] || git checkout $1
[[ -z $1 ]] || exit 0

branch_preview() {
  fzf --header "Checkout Branch" \
  --header-first \
  --preview "git diff --color=always {1} | delta" \
  --preview-label "Branch Preview" \
  --preview-window right,80% \
  --padding 1
}

if [[ -d .git ]]; then
  selected=$(git branch --sort=committerdate | branch_preview)
  [[ -z $selected ]] && exit 0 || git checkout $selected 2> /dev/null
fi
