#!/bin/sh

RED='\033[1;91m'
GREEN='\033[1;32m'
ORANGE='\033[0;33m'
CYAN='\033[0;36m'

[[ "$1" = "-l" ]] && git status --long  2> /dev/null && exit 0

staged_files=$(git diff --name-only --cached 2> /dev/null)
untracked_files=$(git ls-files $(git rev-parse --show-toplevel 2> /dev/null) --exclude-standard --others 2> /dev/null)
dirty_files=$(git ls-files $(git rev-parse --show-toplevel 2> /dev/null) -m 2> /dev/null)

[[ -z $staged_files && -z $untracked_files && -z $dirty_files ]] && exit 0

printf "\n"
echo $staged_files | tr ' ' '\n'| xargs -I {} printf "${GREEN} S  {}\n"
echo $untracked_files | tr ' ' '\n'| xargs -I {} printf "${CYAN} U  {}\n"
echo $dirty_files | tr ' ' '\n'| xargs -I {} printf "${RED} M  {}\n"
