#!/bin/sh

[ -z "$(git rev-parse --show-toplevel 2> /dev/null)" ] && exit 0

ORANGE='\033[0;33m'
RED='\033[0;91m'
WHITE='\033[1;37m'

dirty_preview() {
  fzf -e \
    --preview "git diff --color=always {1} | delta" \
    --preview-window right,60% \
    --bind up:preview-page-up,down:preview-page-down \
    --header "$(printf " ${ORANGE}Open File ")" \
    --header-first \
    --preview-label "$(printf " ${ORANGE}File Preview ")" \
    --border-label "$(printf "${RED} Modified ${WHITE}Files ")" \
    --padding 1 \
    --prompt " " \
    --pointer ""
}

workspace=$(git rev-parse --show-toplevel 2> /dev/null)
dirty_files=$(git diff --name-only --diff-filter=M "$workspace" 2> /dev/null | xargs -I {} printf "${RED}${workspace}/{}\n")
[ -z "$dirty_files" ] && echo "no dirty files, working tree clean" || selected=$(echo "$dirty_files" | tr ' ' '\n' | dirty_preview); [ -z "$selected" ] || nvim "$selected"
