#!/bin/sh

RED='\033[0;91m'
ORANGE='\033[0;33m'
CYAN='\033[0;36m'
fuzzy_preview() {
  fzf -e \
    --delimiter : \
    --preview "bat --theme=1337 --color=always --highlight-line {2} {1}" \
    --preview-window right,70% \
    --bind up:preview-page-up,down:preview-page-down \
    --header "$(printf "${ORANGE}Open File")" \
    --border-label "$(printf " ${CYAN}live-grep ")" \
    --header-first \
    --preview-label "$(printf " ${CYAN}Grep Preview ")" \
    --preview-window '~3,+{2}+3/2'
}

[[ -z $1 ]] && exit 0
selected=$(rg --line-number --only-matching --hidden $1 | fuzzy_preview)
[[ -z $selected ]] && exit 0
filename_and_linenumber=$(echo "${selected%:*}")
filename=$(echo "${filename_and_linenumber%:*}")
linenumber=$(echo "${filename_and_linenumber#*:}")
echo $linenumber
echo $filename
nvim +$linenumber $filename -c 'normal zt'
