#!/bin/sh

ORANGE='\033[0;33m'
CYAN='\033[0;36m'
fuzzy_preview() {
  fzf -e \
    --delimiter : \
    --preview "bat --theme=1337 --color=always --highlight-line {2} {1}" \
    --preview-window right,70% \
    --bind up:preview-page-up,down:preview-page-down \
    --header "$(printf "${ORANGE}Open File")" \
    --border-label "$(printf " ${CYAN}live-grep ")" \
    --header-first \
    --preview-label "$(printf " ${CYAN}Grep Preview ")" \
    --preview-window '~3,+{2}+3/2' \
    --prompt " " \
    --pointer ""
}

[ -z "$1" ] && exit 0
selected=$(rg --line-number --color=always --column --only-matching --hidden --colors "line:fg:green" --colors "column:fg:yellow" --colors "path:fg:blue" --colors "match:fg:white" --glob="!.git" $1 | fuzzy_preview)
[ -z "$selected" ] && exit 0
file_name=$(echo "$selected" | awk -F: '{print $1}')
line_number=$(echo "$selected" | awk -F: '{print $2}')
column_number=$(echo "$selected" | awk -F: '{print $3}')
search_string=$(echo "$selected" | awk -F: '{print $4}')
nvim +"$line_number" -c "normal zt${column_number}|" "+match Search /\%.l${search_string}/" "$file_name"
