#!/bin/sh

switch_shell() {
  selected=$(cat /etc/shells | fzf --border=rounded --margin=10,30)
  [ -z "$selected" ] || chsh -s "$selected"
}

[ $HOSTNAME = "debian" ] && switch_shell
[ $HOSTNAME = "ubuntu" ] && switch_shell
[ $HOSTNAME = "fedora" ] && sudo lchsh "$USER"
