#!/usr/bin/env sh

CYAN='\033[0;36m'
[ -d ~/.dotfiles ] && [ -d ~/.development ] && [ -d ~/.personal ] || exit 0

[ $# -eq 1 ] && selected=$1 || selected=$(find ~/.dotfiles ~/.development ~/.personal -type d | fzf --no-mouse --border-label "$(printf " ${CYAN}tmux-sessionizer ")" --border=rounded --margin=1 --header-first --header "Create tmux session" --prompt "  " --pointer "")

[ -z "$selected" ] && exit 0

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

[ -z "$TMUX" ] && [ -z "$tmux_running" ] && tmux new-session -s "$selected_name" -c "$selected" && exit 0

! tmux has-session -t="$selected_name" 2> /dev/null && tmux new-session -ds "$selected_name" -c "$selected"

tmux has-session -t "$selected_name"

[ -z "$TMUX" ] || tmux switch-client -t "$selected_name"

tmux attach-session -t "$selected_name"
