#!/usr/bin/env sh

[[ -d ~/.dotfiles && -d ~/.development && -d ~/.personal ]] || exit 0

ripgrep() {
  rg ~/.dotfiles ~/.development ~/.personal \
  --files --sort-files --hidden \
    --glob="!{**/.git,**/target,**/node_modules,**/obj}" \
    --null 2> /dev/null | xargs -0 dirname | sort -u
}

# FUZZY FIND DIRECTORIES
[[ $# -eq 1 ]] && selected=$1 || selected=$(ripgrep | fzf --border=rounded --margin=5,10)

# EXITS IF NO SELECTED
[[ -z $selected ]] && exit 0

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# CREATE NEW TMUX SESSION IF TMUX SERVER IS NOT RUNNING
[[ -z $TMUX ]] && [[ -z $tmux_running ]] && tmux new-session -s $selected_name -c $selected && exit 0

# CREATE NEW TMUX SESSION IF THE SELECTED BASENAME IS NOT A SESSION
! tmux has-session -t=$selected_name 2> /dev/null && tmux new-session -ds $selected_name -c $selected

# ATTACH TO TMUX SESSION IF TMUX HAS A SESSION SIMILAR TO SELECTED BASENAME AND IF HAS NO RUNNING TMUX SESSION (OR CURRENTLY DEATTACHED)
tmux has-session -t $selected_name && [[ -z $TMUX ]] && tmux attach-session -t $selected_name || tmux switch-client -t $selected_name 
